export type ReminderLine = { title: string; body: string };

/** 10:00 — breakfast. Body is what shows in the notification. */
export const BREAKFAST: ReminderLine[] = [
  { title: "Breakfast", body: "10:00. The plate happened or it didn't. The log is still empty. Fix that." },
  { title: "Meal one", body: "You ate. The phone did not hear about it. Open Fuel and say what it was." },
  { title: "Log it", body: "Oats, eggs, whey, dahi, air. I don't care which. I care that it is a row." },
  { title: "Still blank", body: "If breakfast was 'I'll remember later', later is a liar. Log it while it is still morning." },
  { title: "Protein", body: "Serious: the day starts when protein is a number, not a vibe. Log meal one." },
  { title: "The log", body: "Your stomach filed the report. Your thumbs did not. Catch up." },
  { title: "Bookkeeping", body: "Three meals in your head, zero in the database. Legendary accounting. Log breakfast." },
  { title: "Hey", body: "The cut does not run on memory. First plate. Now." },
  { title: "Missed it?", body: "Forgot already? Yesterday's button is there. Today's breakfast still needs a row." },
  { title: "No theatre", body: "Don't narrate the oats. Quantity, unit, done. Ten seconds." },
  { title: "Whey counts", body: "A scoop you didn't log is a scoop the week never saw. Breakfast. Log it." },
  { title: "Clock", body: "It is 10. If the first meal is still a story, you are already behind the day." },
  { title: "Roast", body: "You can recall a samosa from 2019 and not the dahi from an hour ago. Open the log." },
  { title: "Angry", body: "Stop walking past Fuel like it owes you money. Breakfast. Row. Go." },
  { title: "Plain", body: "Log what you ate this morning. Include the ghee. Especially the ghee." },
  { title: "Funny", body: "Breakfast called. It said you ghosted it. The app is taking its side." },
  { title: "Check", body: "Dal, eggs, paneer, roti. If it went in, it gets a chip. Morning edition." },
  { title: "Not a mood", body: "Hunger is not a log. A katori count is a log. Do the second one." },
  { title: "Before lunch", body: "Lunch will bury this. Breakfast gets logged before the next plate shows up." },
  { title: "Coach", body: "I'm not mad. I'm the coach who watched you eat and then close the app. Log it." },
  { title: "Empty meters", body: "Energy is at zero because you didn't type, not because you didn't eat. Correct the record." },
  { title: "Short", body: "Breakfast. What. How much. Log." },
  { title: "Oil", body: "The tadka is not free. If breakfast had oil, the row has oil. Go write it." },
  { title: "Repeat", body: "Same plate as yesterday? Tap the chip. New plate? Paste once. Either way, the morning gets a row." },
  { title: "Late honest", body: "Ate at 7, logging at 10. Fine. The day still wants the row before noon erases it." },
  { title: "No vow", body: "No streak speech. One breakfast row. That is the whole assignment." },
  { title: "Mess", body: "Mess thali, home roti, hostel eggs. Name it, size it, save it. Morning is closing." },
  { title: "Soft roast", body: "Future you is going to swear he ate protein. Present you has an empty Today. Settle it." },
  { title: "Direct", body: "Open Fuel. Log breakfast. Then leave. This is not a conversation." },
];

/** 14:00 — lunch. */
export const LUNCH: ReminderLine[] = [
  { title: "Lunch", body: "14:00. Midday plate. If it isn't a row yet, it is about to become a myth." },
  { title: "Afternoon", body: "Rice, roti, dal, paneer. Whatever the mess gave you. Quantity. Log lunch." },
  { title: "Still hungry?", body: "The app is hungry for the truth. You are probably just full and lazy. Log lunch." },
  { title: "Roast", body: "You remembered the score of a match and forgot two katoris of dal. Priorities. Log it." },
  { title: "Serious", body: "Lunch is the meal that blows the day when it stays uncounted. Write it down." },
  { title: "Angry", body: "It is 2. Lunch happened. The log did not. This is the part you keep skipping. Stop." },
  { title: "Breakfast too", body: "While you are here: if breakfast is still blank, that is two lies, not one. Fix both." },
  { title: "Ghee", body: "The second roti and the spoon of ghee are the lunch. Not optional footnotes. Log them." },
  { title: "Funny", body: "Lunch tried to enter the database. You left it on read. Unblock it." },
  { title: "Chip", body: "Same dal as yesterday? The chip is sitting there. Tap, confirm, done." },
  { title: "No guess later", body: "Night-you will invent a calorie number. Afternoon-you still knows the plate. Log lunch now." },
  { title: "Protocol", body: "A real meal gets the protocol tag. A side of namkeen gets junk. Both get logged." },
  { title: "Clock", body: "2pm. Training is later. Carbs you don't log still count. The meter should know." },
  { title: "Short", body: "Lunch. What went in. How many. Save." },
  { title: "Mess tray", body: "If you can't name grams, name katoris and pieces. That is enough. Log the tray." },
  { title: "Coach", body: "Quiet version: the week is the average. An unlogged lunch makes the average fiction." },
  { title: "Roast 2", body: "You'll log a PR set to the plate and forget the actual plate. Lunch. Now." },
  { title: "Oil again", body: "Tadka, pickle, extra roti. Lunch leaks there. Put the leak in the log." },
  { title: "Not later", body: "'After this meeting' is how lunch disappears. Thirty seconds. Fuel. Repeat or JSON." },
  { title: "Direct", body: "Open the app. Log lunch. Include what you actually finished, not what you planned." },
  { title: "Funny 2", body: "Your dal has been waiting at the door like a delivery you won't accept. Let it in." },
  { title: "Angry 2", body: "I don't want a speech about being busy. Busy people still ate. Log the food." },
  { title: "Half day", body: "Half the day is gone. If Today is still empty, you are tracking a fantasy. Start with lunch." },
  { title: "Paneer", body: "Paneer, tofu, eggs, whey, rajma. Protein at lunch or the evening has to rescue you. Log which." },
  { title: "Street", body: "If lunch was a stall, it is still lunch. Junk tag, real quantity, no shame, no skip." },
  { title: "Plain", body: "What did you eat between morning and now? One row each. Go." },
  { title: "Backfill", body: "Wrong day? Step back to yesterday and log it there. Right day? Lunch, this date, this clock." },
  { title: "Meters", body: "The protein meter is not a mood ring. It moves when lunch is a row. Move it." },
  { title: "Last call", body: "This is the afternoon call. Next ping is 11pm, and by then lunch is a blur. Write it." },
];

/** 23:00 — dinner. Close the day. */
export const DINNER: ReminderLine[] = [
  { title: "Dinner", body: "23:00. Day's almost shut. Dinner is either a row or a story you'll argue with tomorrow." },
  { title: "Close it", body: "Before sleep: every plate, the whey, the chai with sugar, the thing you called 'nothing'." },
  { title: "Roast", body: "You will lie down believing the day was clean. The empty log disagrees. Dinner. Now." },
  { title: "Serious", body: "An unclosed day doesn't exist. Log dinner, then look at the meters. That's the day you had." },
  { title: "Angry", body: "It is 11. You ate dinner. You are about to sleep on a blank page. No. Log it." },
  { title: "Funny", body: "Your pillow is not a database. Dinner does not sync overnight. Type it." },
  { title: "The leaks", body: "Night maggi, biscuits, the second serving. If it happened after dark, it still counts. Log it." },
  { title: "All three", body: "Breakfast blank, lunch blank, dinner incoming. That's not a cut. That's amnesia. Start typing." },
  { title: "Protein check", body: "If protein is short, dinner is the last door. Log what you ate, then see the gap for real." },
  { title: "Short", body: "Dinner. Quantity. Save. Sleep." },
  { title: "Ghee, final", body: "Last oil of the day loves to go missing. Put it on the row with the roti." },
  { title: "Coach", body: "Quiet close: no recap essay. The foods. The sizes. Done." },
  { title: "Roast 2", body: "Tomorrow-you is going to be so sure about tonight. Tonight-you should write it down before that guy shows up." },
  { title: "Not a snack hole", body: "If dinner was protocol, tag it protocol. If it was a packet, tag junk. Either way it hits Today." },
  { title: "Clock", body: "11pm. The kitchen is done. The log is not. Finish the second one." },
  { title: "Whey", body: "Post-training scoop still in the shaker and not in the app? That's the row. Log it with dinner." },
  { title: "Funny 2", body: "The day is trying to leave the building. Grab it by the dinner plate and make it sign the sheet." },
  { title: "Angry 2", body: "Don't you dare shut your eyes on an empty Fuel screen. I will still be right. Log dinner." },
  { title: "Yesterday", body: "If this dinner was actually yesterday's, step the day back and log it there. The date matters." },
  { title: "Direct", body: "Open Fuel. Log what you ate tonight. Include the extra. Then you're allowed to sleep." },
  { title: "Meters", body: "Look at kcal and protein after the row, not before. Dinner is what makes the number honest." },
  { title: "Chai", body: "Sweet chai is not water. If the cup had sugar, the day has the cup. Log it." },
  { title: "Plain", body: "Last meal. What was on the plate. How much you finished. One save." },
  { title: "No memory tax", body: "You will not remember this plate on Thursday. Thursday will still be judged by it. Log dinner." },
  { title: "Repeat night", body: "Same eggs and roti as last night? Chip. Different mess? Say it once. Don't skip because you're tired." },
  { title: "Soft", body: "Long day. Still a plate. Thirty seconds keeps the week real. Log dinner." },
  { title: "Final roast", body: "Imagine explaining an empty Tuesday to the mirror. Skip the speech. Enter the food." },
  { title: "Close the door", body: "This is the last ping. After this the day freezes into whatever you typed. Make dinner one of those rows." },
  { title: "Honest", body: "Over the line is allowed. A blank dinner is not. Log the truth and go to bed." },
];
