import type { BodyPart, Drill } from "./types";

export const DRILLS: Drill[] = [
  {
    key: "neck_side",
    name: "Neck side bend",
    parts: ["neck"],
    holdSec: 28,
    bilateral: true,
    do: "Sit or stand tall. Let the ear drift toward the shoulder. Opposite hand can rest. Slow nasal breath. Switch after the hold.",
    avoid: "Do not hike the shoulder to the ear. Do not crank the head with the hand on day one.",
    confirm: "A line from ear to shoulder opens. Jaw unclenches. No pinching at the opposite side of the neck.",
  },
  {
    key: "chin_tuck",
    name: "Chin tucks",
    parts: ["neck"],
    holdSec: 30,
    bilateral: false,
    do: "Eyes level. Slide the chin straight back into a double chin. 8 slow reps inside the hold, 2-second pause at the back.",
    avoid: "Do not look down. Do not shrug. This is a slide, not a nod.",
    confirm: "You feel the front of the neck work and the back of the neck lengthen. Head sits over the ribs, not in front of them.",
  },
  {
    key: "neck_turn",
    name: "Neck rotation",
    parts: ["neck"],
    holdSec: 24,
    bilateral: true,
    do: "Tall spine. Turn the nose toward the shoulder. Pause. Do not force the last degrees.",
    avoid: "No head tilt. No cranking with a hand on the jaw.",
    confirm: "Turn is even left to right. You can still swallow. No dizzy spike.",
  },
  {
    key: "trap_stretch",
    name: "Upper trap stretch",
    parts: ["neck", "shoulders"],
    holdSec: 30,
    bilateral: true,
    do: "Sit on the hand of the stretch side. Tilt the opposite ear away. Soften that shoulder down.",
    avoid: "Do not yank the head. Do not let the sitting-side shoulder creep up.",
    confirm: "A dull line from neck into the trap. Shoulder sits lower than when you started.",
  },
  {
    key: "chest_door",
    name: "Chest doorway",
    parts: ["chest", "shoulders"],
    holdSec: 40,
    bilateral: true,
    do: "Forearm on the frame, elbow near shoulder height. Step the same-side foot through. Ribs down. Breathe into the pec.",
    avoid: "Do not flare the ribs or arch the low back to fake range.",
    confirm: "Pec and front shoulder open. You can still stack ribs over pelvis. No pinching in the front of the shoulder.",
  },
  {
    key: "chest_chair",
    name: "Chest opener",
    parts: ["chest"],
    holdSec: 38,
    bilateral: false,
    do: "Hands clasped behind a chair or low back. Open the chest. Soft elbows. Look forward.",
    avoid: "Do not dump into the lumbar. Do not shrug to the ears.",
    confirm: "Breath goes into the upper chest and pecs. Shoulders sit back without pain in the neck.",
  },
  {
    key: "pec_floor",
    name: "Floor pec",
    parts: ["chest"],
    holdSec: 32,
    bilateral: true,
    do: "Lie on the stretch-side pec, arm out about 90°. Slow. Turn the chest slightly away.",
    avoid: "Do not smash the front of the shoulder into the floor.",
    confirm: "Pec lengthens. Arm can stay heavy. No sharp front-shoulder bite.",
  },
  {
    key: "tri_overhead",
    name: "Overhead tricep",
    parts: ["shoulders"],
    holdSec: 28,
    bilateral: true,
    do: "Elbow to the sky. Other hand on that elbow. Ribs stacked. Reach the hand down the spine.",
    avoid: "Do not flare the ribcage. Do not crank the neck forward.",
    confirm: "Tricep and lats feel long. You can still see forward without the chin poking.",
  },
  {
    key: "shoulder_cross",
    name: "Cross-body shoulder",
    parts: ["shoulders"],
    holdSec: 26,
    bilateral: true,
    do: "Arm across the chest. Pull at the elbow. Chest stays open. Trap down.",
    avoid: "Do not roll the shoulder forward. Do not yank the elbow past comfort.",
    confirm: "Rear delt / capsule stretch, not a neck stretch. Both shoulders level.",
  },
  {
    key: "rear_delt",
    name: "Rear delt",
    parts: ["shoulders"],
    holdSec: 28,
    bilateral: true,
    do: "Arm across. Pull at the elbow. Think elbow toward the opposite armpit. Chest proud.",
    avoid: "Do not collapse the chest. Do not turn it into a neck crank.",
    confirm: "You feel the back of the shoulder, not the trap hiking.",
  },
  {
    key: "scap_wall",
    name: "Wall slides",
    parts: ["shoulders", "thoracic"],
    holdSec: 35,
    bilateral: false,
    do: "Back to wall, ribs down. Forearms on the wall. Slide up and down 8 slow reps. Keep low back close.",
    avoid: "Do not arch to get the arms up. Do not shrug the first inch.",
    confirm: "Arms travel without the ribs flaring. Shoulder blades glide, they do not jam.",
  },
  {
    key: "lat_reach",
    name: "Lat side reach",
    parts: ["lats"],
    holdSec: 30,
    bilateral: true,
    do: "One arm overhead. Lean away. Same-side hip heavy. Reach long through the fingers.",
    avoid: "Do not crunch the opposite waist as a cheat. Do not twist the chest closed.",
    confirm: "A long line from hip to armpit. Breath can still go into that side.",
  },
  {
    key: "lat_hang",
    name: "Hang or doorway lat",
    parts: ["lats", "shoulders"],
    holdSec: 32,
    bilateral: false,
    do: "Bar hang, shoulders away from ears. No bar: both hands on a doorframe, sit the hips back.",
    avoid: "Do not dump into a dead hang if the shoulders scream. Do not hang from the neck.",
    confirm: "Lats and armpit walls lengthen. You can still pack the shoulders slightly.",
  },
  {
    key: "bicep_wall",
    name: "Bicep wall",
    parts: ["shoulders"],
    holdSec: 32,
    bilateral: true,
    do: "Arm extended back, palm on a rack or wall, elbow soft. Turn the chest away a few degrees.",
    avoid: "Do not lock the elbow hard. Do not twist the wrist into a weird angle.",
    confirm: "Bicep and front shoulder open. Elbow stays happy.",
  },
  {
    key: "thoracic_seated",
    name: "Seated thoracic turn",
    parts: ["thoracic"],
    holdSec: 24,
    bilateral: true,
    do: "Hands at the chest. Rotate from the mid-back. Eyes follow. Sit bones stay heavy.",
    avoid: "Do not turn only the neck. Do not lift one sit bone.",
    confirm: "You feel the ribcage turn. Neck is along for the ride, not the engine.",
  },
  {
    key: "thoracic_quad",
    name: "Quadruped T-spine",
    parts: ["thoracic"],
    holdSec: 40,
    bilateral: true,
    do: "Hand behind the head. Elbow toward the floor, then to the sky. 8 slow reps per side inside the hold.",
    avoid: "Do not collapse the supporting shoulder. Do not shove the low back into a sag.",
    confirm: "The elbow tracks a bigger arc than yesterday. Breathing stays easy at the top.",
  },
  {
    key: "thread_needle",
    name: "Thread the needle",
    parts: ["thoracic", "shoulders"],
    holdSec: 30,
    bilateral: true,
    do: "On all fours. Slide one arm under the other. Rest the shoulder. Breathe into the upper back.",
    avoid: "Do not dump all weight onto the neck. Do not force the shoulder to the floor.",
    confirm: "Mid-back and rear shoulder open. You can still push the floor away with the planted hand.",
  },
  {
    key: "cat_cow",
    name: "Cat-cow",
    parts: ["thoracic", "low_back"],
    holdSec: 50,
    bilateral: false,
    do: "Hands under shoulders, knees under hips. 10 slow reps. Full round, full arch. Neck follows the spine.",
    avoid: "Do not dump into a hard lumbar arch. Do not hold the breath.",
    confirm: "Every vertebra feels like it moved a little. Wrists comfortable, or fists / pads if not.",
  },
  {
    key: "child_pose",
    name: "Child's pose",
    parts: ["lats", "low_back"],
    holdSec: 40,
    bilateral: false,
    do: "Hips to heels. Arms long. Walk hands to one side then the other halfway. Nasal breath into the back.",
    avoid: "Do not force the butt to the heels if the knees hate it. Widen the knees.",
    confirm: "Low back and lats settle. Heart rate comes down. Shoulders melt away from the ears.",
  },
  {
    key: "worlds",
    name: "World's greatest stretch",
    parts: ["hips", "thoracic", "hamstrings"],
    holdSec: 44,
    bilateral: true,
    do: "Lunge. Elbow inside the front foot, then rotate the chest to the sky. Front heel stays down.",
    avoid: "Do not let the front knee collapse in. Do not bounce.",
    confirm: "Hip, hamstring, and T-spine all talk. You can rotate without the back knee screaming.",
  },
  {
    key: "hip_circles",
    name: "Hip circles",
    parts: ["hips"],
    holdSec: 26,
    bilateral: true,
    do: "Standing. Hand on a wall. 10 slow circles each direction. Draw a big, quiet circle with the knee.",
    avoid: "Do not swing from the low back. Do not race.",
    confirm: "The hip joint feels oiled. Circle is round, not a slash.",
  },
  {
    key: "hip_flexor",
    name: "Hip flexor lunge",
    parts: ["hips", "quads"],
    holdSec: 36,
    bilateral: true,
    do: "Back knee down. Tuck the tail. Shift forward until the front of the hip opens. Desk or floor for balance.",
    avoid: "Do not crank from the lumbar. The stretch is the hip, not a backbend.",
    confirm: "Front of the hip (psoas/rectus) talks. Glute of the back leg can squeeze without the low back grabbing.",
  },
  {
    key: "couch",
    name: "Couch stretch",
    parts: ["hips", "quads"],
    holdSec: 38,
    bilateral: true,
    do: "Back foot up a wall or couch. Tuck pelvis. Tall. Only as close as the hip allows.",
    avoid: "Do not let the low back scream to get upright. Pad the back knee.",
    confirm: "Quad and hip flexor, not lumbar. You can brace the abs and still feel the stretch.",
  },
  {
    key: "pigeon",
    name: "Pigeon",
    parts: ["glutes", "hips"],
    holdSec: 40,
    bilateral: true,
    do: "Front shin as square as you have. Hinge over. Flex the front foot. Breathe.",
    avoid: "Do not force a square shin. Do not roll onto the outside of the knee.",
    confirm: "Glute and hip capsule, not a stab in the knee. You can still breathe into the belly.",
  },
  {
    key: "fig4",
    name: "Figure-4",
    parts: ["glutes"],
    holdSec: 32,
    bilateral: true,
    do: "Ankle on opposite knee, sitting or lying. Hinge. Keep the lifted foot flexed.",
    avoid: "Do not pull the knee into a weird twist. Do not shrug.",
    confirm: "Outer glute / piriformis. The standing or down hip stays quiet.",
  },
  {
    key: "hip90",
    name: "90/90 sit",
    parts: ["hips"],
    holdSec: 32,
    bilateral: true,
    do: "Both knees 90. Sit tall. Lean toward the front shin. Switch the pair after.",
    avoid: "Do not collapse the chest. Do not let the back hip sneak out of 90.",
    confirm: "Both hips work. You can sit taller than when you started the hold.",
  },
  {
    key: "butterfly",
    name: "Butterfly",
    parts: ["adductors"],
    holdSec: 38,
    bilateral: false,
    do: "Soles together. Tall spine. Knees fall. Elbows can rest, no bounce.",
    avoid: "Do not push the knees with force. Do not round into a slump.",
    confirm: "Inner thighs open evenly. You can still sit on the sit bones, not the tailbone.",
  },
  {
    key: "frog",
    name: "Frog rock",
    parts: ["adductors", "hips"],
    holdSec: 36,
    bilateral: false,
    do: "Knees wide, shins out. Rock back and forth 8 slow times, then hold. Hips to heels as far as they go.",
    avoid: "Do not let the low back sag. Stop if the knees complain — pad them.",
    confirm: "Adductors and hips share the work. Knees stay friendly.",
  },
  {
    key: "cossack",
    name: "Cossack sit",
    parts: ["adductors", "hips"],
    holdSec: 28,
    bilateral: true,
    do: "Wide stance. Sit to one side, other leg long, toes up. Hold. Hands on the floor if needed.",
    avoid: "Do not collapse the standing knee in. Do not force the long heel if the hamstring is not ready.",
    confirm: "Adductor of the long leg and hip of the bent leg. You can still see the toes of the long foot.",
  },
  {
    key: "quad_stand",
    name: "Standing quad",
    parts: ["quads"],
    holdSec: 30,
    bilateral: true,
    do: "Heel to glute. Knees together. Squeeze the glute of the stretch side. Tall.",
    avoid: "Do not crank the knee. Do not flare the ribs to stand up.",
    confirm: "Quad lengthens because the hip is extended, not because you yanked the foot.",
  },
  {
    key: "ham_hinge",
    name: "Hamstring hinge",
    parts: ["hamstrings"],
    holdSec: 36,
    bilateral: true,
    do: "Soft knee. Hinge from the hips. Long spine. Hands on a wall or the shin — do not chase the floor.",
    avoid: "Do not round the low back to touch the ground. That is not a hamstring stretch.",
    confirm: "You feel the belly of the hamstring, not a stab behind the knee. Spine stays long.",
  },
  {
    key: "calf_wall",
    name: "Calf wall",
    parts: ["calves"],
    holdSec: 30,
    bilateral: true,
    do: "Heel down. Rear leg straight first, then a slight knee bend for soleus. Hip stacked.",
    avoid: "Do not let the heel pop. Do not turn the foot out to cheat.",
    confirm: "Calf (then soleus) loads. Heel stays heavy. Ankle does not collapse in.",
  },
  {
    key: "soleus",
    name: "Soleus bend",
    parts: ["calves", "ankles"],
    holdSec: 28,
    bilateral: true,
    do: "Same wall lean, but both knees bent. Heel glued. You should feel lower, closer to the Achilles.",
    avoid: "Do not lift the heel to get a stretch. Do not bounce.",
    confirm: "The stretch sits lower than a straight-leg calf. Ankle still tracks over the second toe.",
  },
  {
    key: "ankle_rock",
    name: "Ankle rocks",
    parts: ["ankles"],
    holdSec: 30,
    bilateral: true,
    do: "Half-kneel. Drive the front knee over the toes, heel down. 10 slow rocks, then hold the deepest honest position.",
    avoid: "Do not let the knee dive in. Do not lift the heel.",
    confirm: "Knee can travel past the toes with the heel down. No pinch in the front of the ankle — if there is, back off a few degrees.",
  },
  {
    key: "wrist_desk",
    name: "Wrist stretch",
    parts: ["wrists"],
    holdSec: 28,
    bilateral: false,
    do: "Palm up on the desk edge, then palm down. Gentle. Fingers back, then fingers toward you.",
    avoid: "Do not dump bodyweight into a locked elbow. Do not force a loaded wrist if it is already angry from court.",
    confirm: "Forearm and wrist open in both directions. Fingers can still wiggle.",
  },
  {
    key: "wrist_prayer",
    name: "Prayer and reverse",
    parts: ["wrists"],
    holdSec: 26,
    bilateral: false,
    do: "Palms together at the chest, lower the hands. Then backs of the hands together. Slow.",
    avoid: "Do not shrug. Do not force if the wrists are hot after badminton.",
    confirm: "Equal left and right. You can keep the heels of the hands together without the fingers splaying in panic.",
  },
];

export const DRILL_MAP = new Map(DRILLS.map((d) => [d.key, d]));

export function getDrill(key: string): Drill | undefined {
  return DRILL_MAP.get(key);
}

export const PART_NEAR: Record<BodyPart, BodyPart[]> = {
  neck: ["shoulders", "thoracic"],
  shoulders: ["chest", "thoracic", "lats"],
  chest: ["shoulders", "thoracic"],
  lats: ["thoracic", "shoulders", "low_back"],
  thoracic: ["shoulders", "lats", "neck"],
  low_back: ["hips", "glutes", "hamstrings", "thoracic"],
  hips: ["glutes", "quads", "hamstrings", "adductors"],
  glutes: ["hips", "hamstrings"],
  quads: ["hips", "calves"],
  hamstrings: ["glutes", "calves", "hips"],
  adductors: ["hips", "glutes"],
  calves: ["ankles", "hamstrings"],
  ankles: ["calves", "hips"],
  wrists: ["shoulders"],
};
